#!/usr/bin/python

"""
DGEParser.py

Parse DGE files generated by Drop-seq experiment (Accepts DGE matrix generated by Drop-seq_tools-1.12)

Assumed row is gene and column is cell

Author : Sunghoon Heo
"""

class DGELineRecord:
	def __init__(self, line,gene_label = None):
		if gene_label == None:
			self.proc_without_gene_label(line)
		else:
			self.proc_with_gene_label(line)
			
	def proc_without_gene_label(self, s):
		data = line.rstrip().split(s)
		self.cols = len(data)
		
